import { Avatar_01, Avatar_03, Avatar_04 } from "../../../../../Routes/ImagePath";

export const paySlipData = [
  {
    id: 1,
    employeeId: "EMP001",
    image: Avatar_03,
    name: "John Doe",
    role: "Web Developer",
    amount: "$200",
    paymentmonth: "Apr",
    paymentyear: "2019",
  },
  {
    id: 2,
    employeeId: "EMP002",
    image: Avatar_04,
    name: "Richard Miles",
    role: "Android Developer",
    amount: "$300",
    paymentmonth: "Dec",
    paymentyear: "2023",
  },
  {
    id: 3,
    employeeId: "EMP003",
    image: Avatar_01,
    name: "Michael",
    role: "IOS Developer",
    amount: "$350",
    paymentmonth: "Jan",
    paymentyear: "2023",
  },
  {
    id: 4,
    employeeId: "EMP004",
    image: Avatar_03,
    name: "Sarah Smith",
    role: "UI/UX Designer",
    amount: "$250",
    paymentmonth: "Feb",
    paymentyear: "2023",
  },
  {
    id: 5,
    employeeId: "EMP005",
    image: Avatar_04,
    name: "David Johnson",
    role: "Backend Developer",
    amount: "$400",
    paymentmonth: "Mar",
    paymentyear: "2023",
  },
  {
    id: 6,
    employeeId: "EMP006",
    image: Avatar_01,
    name: "Emily Clark",
    role: "QA Engineer",
    amount: "$220",
    paymentmonth: "May",
    paymentyear: "2019",
  },
  {
    id: 7,
    employeeId: "EMP007",
    image: Avatar_03,
    name: "Chris Lee",
    role: "Project Manager",
    amount: "$500",
    paymentmonth: "Jun",
    paymentyear: "2023",
  },
  {
    id: 8,
    employeeId: "EMP008",
    image: Avatar_04,
    name: "Anna Brown",
    role: "HR Manager",
    amount: "$320",
    paymentmonth: "Jul",
    paymentyear: "2023",
  },
  {
    id: 9,
    employeeId: "EMP009",
    image: Avatar_01,
    name: "James Wilson",
    role: "DevOps Engineer",
    amount: "$380",
    paymentmonth: "Aug",
    paymentyear: "2023",
  },
  {
    id: 10,
    employeeId: "EMP010",
    image: Avatar_03,
    name: "Olivia Martinez",
    role: "Frontend Developer",
    amount: "$270",
    paymentmonth: "Sep",
    paymentyear: "2023",
  },
  {
    id: 11,
    employeeId: "EMP011",
    image: Avatar_04,
    name: "William Anderson",
    role: "Business Analyst",
    amount: "$330",
    paymentmonth: "Oct",
    paymentyear: "2023",
  },
  {
    id: 12,
    employeeId: "EMP012",
    image: Avatar_01,
    name: "Sophia Thomas",
    role: "Content Writer",
    amount: "$210",
    paymentmonth: "Nov",
    paymentyear: "2023",
  },
];