import { Avatar_02, Avatar_05, Avatar_09 } from "../../../../../Routes/ImagePath";

export const employeeData = [
  {
    id: 1,
    image: Avatar_02,
    name: "John Doe",
    number: "#0001",
    employeetype: "Employee",
    email: "johndoe@example.com",
    department: "Design",
    designation: "UI Design",
    joiningdate: "20 Aug 2023",
    dob: "03 Mar 1992",
    maritalstatus: "Married",
    gender: "Male",
    terminateddate: "-",
    relievingdate: "-",
    salary: "$20000",
    address: "1861 Bayonne Ave, Manchester Township, NJ, 08759",
    contactnumber: "9876543210",
    emergencycontactdetails: "7894561235",
    experience: "0 years 4 months 9 days",
  },
  {
    id: 2,
    image: Avatar_05,
    name: "Richard Miles",
    number: "#0002",
    employeetype: "Employee",
    email: "richardmiles@example.com",
    department: "Android Developer",
    designation: "IT Support",
    joiningdate: "01 Jul 2023",
    dob: "05 Dec 1979",
    maritalstatus: "Single",
    gender: "Male",
    terminateddate: "-",
    relievingdate: "-",
    salary: "$15000",
    address: "1861 Bayonne Ave, Manchester Township, NJ, 08759",
    contactnumber: "9876543210",
    emergencycontactdetails: "7894561235",
    experience: "0 years 5 months 24 days",
  },
  {
    id: 3,
    image: Avatar_09,
    name: "Mike Litorous",
    number: "#0004",
    employeetype: "Employee",
    email: "mikelitorous@example.com",
    department: "IOS Developer",
    designation: "IT Support",
    joiningdate: "01 Jul 2023",
    dob: "05 Jan 1981",
    maritalstatus: "Single",
    gender: "Male",
    terminateddate: "-",
    relievingdate: "-",
    salary: "$16000",
    address: "1920 Bayonne Ave, Flat Township, NJ, 21345",
    contactnumber: "9764536733",
    emergencycontactdetails: "7894561235",
    experience: "4 years 3 months 8 days",
  },
  {
    id: 4,
    image: Avatar_05,
    name: "Linda Barrett",
    number: "#0005",
    employeetype: "Employee",
    email: "lindabarrett@example.com",
    department: "Design",
    designation: "Graphic Designer",
    joiningdate: "15 Sep 2022",
    dob: "12 Nov 1990",
    maritalstatus: "Married",
    gender: "Female",
    terminateddate: "-",
    relievingdate: "-",
    salary: "$18000",
    address: "1234 Elm St, Springfield, IL, 62704",
    contactnumber: "9123456789",
    emergencycontactdetails: "9988776655",
    experience: "1 years 3 months 14 days",
  },
  {
    id: 5,
    image: Avatar_02,
    name: "Michael Scott",
    number: "#0006",
    employeetype: "Employee",
    email: "michaelscott@example.com",
    department: "Android Developer",
    designation: "Project Manager",
    joiningdate: "10 Jan 2021",
    dob: "15 Mar 1985",
    maritalstatus: "Married",
    gender: "Male",
    terminateddate: "-",
    relievingdate: "-",
    salary: "$25000",
    address: "1725 Slough Ave, Scranton, PA, 18505",
    contactnumber: "9001122334",
    emergencycontactdetails: "9112233445",
    experience: "2 years 11 months 19 days",
  },
  {
    id: 6,
    image: Avatar_09,
    name: "Pam Beesly",
    number: "#0007",
    employeetype: "Employee",
    email: "pambeesly@example.com",
    department: "Design",
    designation: "Receptionist",
    joiningdate: "05 May 2022",
    dob: "25 Jun 1991",
    maritalstatus: "Married",
    gender: "Female",
    terminateddate: "-",
    relievingdate: "-",
    salary: "$12000",
    address: "4567 Maple Dr, Scranton, PA, 18505",
    contactnumber: "9876543211",
    emergencycontactdetails: "9123456780",
    experience: "1 years 7 months 24 days",
  },
  {
    id: 7,
    image: Avatar_05,
    name: "Jim Halpert",
    number: "#0008",
    employeetype: "Employee",
    email: "jimhalpert@example.com",
    department: "IOS Developer",
    designation: "Salesman",
    joiningdate: "12 Feb 2020",
    dob: "01 Oct 1988",
    maritalstatus: "Married",
    gender: "Male",
    terminateddate: "-",
    relievingdate: "-",
    salary: "$17000",
    address: "7890 Oak St, Scranton, PA, 18505",
    contactnumber: "9988776654",
    emergencycontactdetails: "9001122335",
    experience: "3 years 10 months 17 days",
  },
  {
    id: 8,
    image: Avatar_02,
    name: "Angela Martin",
    number: "#0009",
    employeetype: "Employee",
    email: "angelamartin@example.com",
    department: "Design",
    designation: "Accountant",
    joiningdate: "22 Mar 2019",
    dob: "17 Sep 1982",
    maritalstatus: "Single",
    gender: "Female",
    terminateddate: "-",
    relievingdate: "-",
    salary: "$14000",
    address: "321 Pine St, Scranton, PA, 18505",
    contactnumber: "9112233446",
    emergencycontactdetails: "9876543212",
    experience: "4 years 9 months 7 days",
  },
  {
    id: 9,
    image: Avatar_09,
    name: "Stanley Hudson",
    number: "#0010",
    employeetype: "Employee",
    email: "stanleyhudson@example.com",
    department: "Android Developer",
    designation: "Sales Representative",
    joiningdate: "30 Nov 2018",
    dob: "19 Feb 1970",
    maritalstatus: "Married",
    gender: "Male",
    terminateddate: "-",
    relievingdate: "-",
    salary: "$15500",
    address: "654 Cedar St, Scranton, PA, 18505",
    contactnumber: "9009988776",
    emergencycontactdetails: "9988776653",
    experience: "5 years 0 months 29 days",
  },
  {
    id: 10,
    image: Avatar_05,
    name: "Kelly Kapoor",
    number: "#0011",
    employeetype: "Employee",
    email: "kellykapoor@example.com",
    department: "IOS Developer",
    designation: "Customer Service Rep",
    joiningdate: "18 Jun 2021",
    dob: "24 Feb 1987",
    maritalstatus: "Single",
    gender: "Female",
    terminateddate: "-",
    relievingdate: "-",
    salary: "$13000",
    address: "987 Willow St, Scranton, PA, 18505",
    contactnumber: "9112233447",
    emergencycontactdetails: "9001122336",
    experience: "2 years 6 months 11 days",
  },
  // Additional data
  {
    id: 11,
    image: Avatar_02,
    name: "Oscar Martinez",
    number: "#0012",
    employeetype: "Employee",
    email: "oscarmartinez@example.com",
    department: "Design",
    designation: "Accountant",
    joiningdate: "10 Oct 2017",
    dob: "12 Apr 1980",
    maritalstatus: "Single",
    gender: "Male",
    terminateddate: "-",
    relievingdate: "-",
    salary: "$14500",
    address: "123 Birch St, Scranton, PA, 18505",
    contactnumber: "9001122338",
    emergencycontactdetails: "9112233449",
    experience: "6 years 2 months 19 days",
  },
  {
    id: 12,
    image: Avatar_05,
    name: "Phyllis Vance",
    number: "#0013",
    employeetype: "Employee",
    email: "phyllisvance@example.com",
    department: "Android Developer",
    designation: "Sales Representative",
    joiningdate: "15 Mar 2016",
    dob: "10 Jul 1965",
    maritalstatus: "Married",
    gender: "Female",
    terminateddate: "-",
    relievingdate: "-",
    salary: "$13500",
    address: "456 Spruce St, Scranton, PA, 18505",
    contactnumber: "9876543213",
    emergencycontactdetails: "9001122339",
    experience: "7 years 9 months 14 days",
  },
  {
    id: 13,
    image: Avatar_09,
    name: "Creed Bratton",
    number: "#0014",
    employeetype: "Employee",
    email: "creedbratton@example.com",
    department: "IOS Developer",
    designation: "Quality Assurance",
    joiningdate: "01 Jan 2015",
    dob: "01 Feb 1950",
    maritalstatus: "Single",
    gender: "Male",
    terminateddate: "-",
    relievingdate: "-",
    salary: "$12000",
    address: "789 Aspen St, Scranton, PA, 18505",
    contactnumber: "9112233450",
    emergencycontactdetails: "9876543214",
    experience: "9 years 0 months 28 days",
  },
  {
    id: 14,
    image: Avatar_02,
    name: "Meredith Palmer",
    number: "#0015",
    employeetype: "Employee",
    email: "meredithpalmer@example.com",
    department: "Design",
    designation: "Supplier Relations",
    joiningdate: "20 Aug 2018",
    dob: "15 May 1972",
    maritalstatus: "Divorced",
    gender: "Female",
    terminateddate: "-",
    relievingdate: "-",
    salary: "$11000",
    address: "321 Maple St, Scranton, PA, 18505",
    contactnumber: "9001122340",
    emergencycontactdetails: "9112233451",
    experience: "5 years 4 months 9 days",
  },
  {
    id: 15,
    image: Avatar_05,
    name: "Ryan Howard",
    number: "#0016",
    employeetype: "Employee",
    email: "ryanhoward@example.com",
    department: "Android Developer",
    designation: "Temp",
    joiningdate: "01 Sep 2022",
    dob: "27 May 1984",
    maritalstatus: "Single",
    gender: "Male",
    terminateddate: "-",
    relievingdate: "-",
    salary: "$9000",
    address: "654 Oak St, Scranton, PA, 18505",
    contactnumber: "9876543215",
    emergencycontactdetails: "9001122341",
    experience: "1 years 3 months 28 days",
  },
  {
    id: 16,
    image: Avatar_09,
    name: "Toby Flenderson",
    number: "#0017",
    employeetype: "Employee",
    email: "tobyflenderson@example.com",
    department: "IOS Developer",
    designation: "HR",
    joiningdate: "10 Feb 2014",
    dob: "22 Aug 1971",
    maritalstatus: "Divorced",
    gender: "Male",
    terminateddate: "-",
    relievingdate: "-",
    salary: "$12500",
    address: "987 Elm St, Scranton, PA, 18505",
    contactnumber: "9112233452",
    emergencycontactdetails: "9876543216",
    experience: "9 years 10 months 19 days",
  },
  {
    id: 17,
    image: Avatar_02,
    name: "Darryl Philbin",
    number: "#0018",
    employeetype: "Employee",
    email: "darrylphilbin@example.com",
    department: "Design",
    designation: "Warehouse Manager",
    joiningdate: "05 May 2013",
    dob: "15 Jun 1978",
    maritalstatus: "Married",
    gender: "Male",
    terminateddate: "-",
    relievingdate: "-",
    salary: "$16000",
    address: "123 Warehouse Rd, Scranton, PA, 18505",
    contactnumber: "9001122342",
    emergencycontactdetails: "9112233453",
    experience: "10 years 7 months 24 days",
  },
  {
    id: 18,
    image: Avatar_05,
    name: "Erin Hannon",
    number: "#0019",
    employeetype: "Employee",
    email: "erinhannon@example.com",
    department: "Android Developer",
    designation: "Receptionist",
    joiningdate: "15 Jan 2020",
    dob: "07 Jun 1990",
    maritalstatus: "Single",
    gender: "Female",
    terminateddate: "-",
    relievingdate: "-",
    salary: "$9500",
    address: "456 Reception St, Scranton, PA, 18505",
    contactnumber: "9876543217",
    emergencycontactdetails: "9001122343",
    experience: "3 years 11 months 14 days",
  },
  {
    id: 19,
    image: Avatar_09,
    name: "Jan Levinson",
    number: "#0020",
    employeetype: "Employee",
    email: "janlevinson@example.com",
    department: "IOS Developer",
    designation: "VP Sales",
    joiningdate: "01 Apr 2012",
    dob: "11 Mar 1970",
    maritalstatus: "Divorced",
    gender: "Female",
    terminateddate: "-",
    relievingdate: "-",
    salary: "$30000",
    address: "789 Corporate Ave, Scranton, PA, 18505",
    contactnumber: "9112233454",
    emergencycontactdetails: "9876543218",
    experience: "11 years 8 months 28 days",
  },
  {
    id: 20,
    image: Avatar_02,
    name: "Holly Flax",
    number: "#0021",
    employeetype: "Employee",
    email: "hollyflax@example.com",
    department: "Design",
    designation: "HR",
    joiningdate: "10 Oct 2018",
    dob: "19 Dec 1973",
    maritalstatus: "Married",
    gender: "Female",
    terminateddate: "-",
    relievingdate: "-",
    salary: "$13500",
    address: "321 HR St, Scranton, PA, 18505",
    contactnumber: "9001122344",
    emergencycontactdetails: "9112233455",
    experience: "5 years 2 months 19 days",
  },
];