import { Avatar_16 } from "../../../../../Routes/ImagePath";

export const taskData = [
  {
    id: "1",
    category: "Hospital Administration",
    startDate: "26 Mar 2023",
    endDate: "26 Apr 2023",
    status: "Active",
    name: "Jeffery Lalor",
    image: Avatar_16,
  },
  {
    id: "2",
    category: "Office Management",
    startDate: "27 Mar 2023",
    endDate: "27 Apr 2023",
    status: "Inactive",
    name: "John Smith",
    image: Avatar_16,
  },
  {
    id: "3",
    category: "Project Management",
    startDate: "28 Mar 2023",
    endDate: "28 Apr 2023",
    status: "Active",
    name: "Richard Miles",
    image: Avatar_16,
  },
  {
    id: "4",
    category: "Inventory Control",
    startDate: "29 Mar 2023",
    endDate: "29 Apr 2023",
    status: "Active",
    name: "Catherine Manseau",
    image: Avatar_16,
  },
  {
    id: "5",
    category: "Patient Care",
    startDate: "30 Mar 2023",
    endDate: "30 Apr 2023",
    status: "Inactive",
    name: "Barry Cuda",
    image: Avatar_16,
  },
  {
    id: "6",
    category: "Staff Scheduling",
    startDate: "31 Mar 2023",
    endDate: "01 May 2023",
    status: "Active",
    name: "Linda Barrett",
    image: Avatar_16,
  },
  {
    id: "7",
    category: "Facility Maintenance",
    startDate: "01 Apr 2023",
    endDate: "01 May 2023",
    status: "Inactive",
    name: "Wilmer Deluna",
    image: Avatar_16,
  },
  {
    id: "8",
    category: "Medical Billing",
    startDate: "02 Apr 2023",
    endDate: "02 May 2023",
    status: "Active",
    name: "Lesley Grauer",
    image: Avatar_16,
  },
  {
    id: "9",
    category: "Compliance Audit",
    startDate: "03 Apr 2023",
    endDate: "03 May 2023",
    status: "Inactive",
    name: "Jeffery Lalor",
    image: Avatar_16,
  },
  {
    id: "10",
    category: "Training & Development",
    startDate: "04 Apr 2023",
    endDate: "04 May 2023",
    status: "Active",
    name: "John Smith",
    image: Avatar_16,
  },
  {
    id: "11",
    category: "IT Support",
    startDate: "05 Apr 2023",
    endDate: "05 May 2023",
    status: "Inactive",
    name: "Richard Miles",
    image: Avatar_16,
  },
  {
    id: "12",
    category: "Procurement",
    startDate: "06 Apr 2023",
    endDate: "06 May 2023",
    status: "Active",
    name: "Catherine Manseau",
    image: Avatar_16,
  },
  {
    id: "13",
    category: "Payroll Processing",
    startDate: "07 Apr 2023",
    endDate: "07 May 2023",
    status: "Inactive",
    name: "Barry Cuda",
    image: Avatar_16,
  },
  {
    id: "14",
    category: "Customer Service",
    startDate: "08 Apr 2023",
    endDate: "08 May 2023",
    status: "Active",
    name: "Linda Barrett",
    image: Avatar_16,
  },
  {
    id: "15",
    category: "Quality Assurance",
    startDate: "09 Apr 2023",
    endDate: "09 May 2023",
    status: "Inactive",
    name: "Wilmer Deluna",
    image: Avatar_16,
  },
];