import { Avatar_19, Avatar_21 } from "../../../../../Routes/ImagePath";

export const userData = [
  {
    id: "1",
    name: "Barry Cuda",
    company: "Global Technologies",
    email: "barrycuda@example.com",
    role: "CEO",
    status: "Active",
    type: "Client",
    image: Avatar_19,
  },
  {
    id: "2",
    name: "Daniel Porter",
    company: "Focus Technologies",
    email: "danielporter@example.com",
    role: "Admin Manager",
    status: "Active",
    type: "Admin",
    image: Avatar_21,
  },
  {
    id: "3",
    name: "John Smith",
    company: "Delta Infotech",
    email: "johnsmith@example.com",
    role: "Developer",
    status: "Inactive",
    type: "Employee",
    image: Avatar_19,
  },
  {
    id: "4",
    name: "Richard Miles",
    company: "Dreamguy's Technologies",
    email: "richardmiles@example.com",
    role: "Team Leader",
    status: "Active",
    type: "Employee",
    image: Avatar_21,
  },
  {
    id: "5",
    name: "Linda Barrett",
    company: "Tech Solutions",
    email: "lindabarrett@example.com",
    role: "HR Manager",
    status: "Active",
    type: "Admin",
    image: Avatar_19,
  },
  {
    id: "6",
    name: "Michael Scott",
    company: "Dunder Mifflin",
    email: "michaelscott@example.com",
    role: "Regional Manager",
    status: "Inactive",
    type: "Client",
    image: Avatar_21,
  },
  {
    id: "7",
    name: "Pam Beesly",
    company: "Dunder Mifflin",
    email: "pambeesly@example.com",
    role: "Receptionist",
    status: "Active",
    type: "Employee",
    image: Avatar_19,
  },
  {
    id: "8",
    name: "Jim Halpert",
    company: "Dunder Mifflin",
    email: "jimhalpert@example.com",
    role: "Salesman",
    status: "Active",
    type: "Employee",
    image: Avatar_21,
  },
  {
    id: "9",
    name: "Angela Martin",
    company: "Dunder Mifflin",
    email: "angelamartin@example.com",
    role: "Accountant",
    status: "Inactive",
    type: "Employee",
    image: Avatar_19,
  },
  {
    id: "10",
    name: "Dwight Schrute",
    company: "Dunder Mifflin",
    email: "dwightschrute@example.com",
    role: "Assistant to the Regional Manager",
    status: "Active",
    type: "Employee",
    image: Avatar_21,
  },
  {
    id: "11",
    name: "Oscar Martinez",
    company: "Dunder Mifflin",
    email: "oscarmartinez@example.com",
    role: "Accountant",
    status: "Active",
    type: "Employee",
    image: Avatar_19,
  },
  {
    id: "12",
    name: "Stanley Hudson",
    company: "Dunder Mifflin",
    email: "stanleyhudson@example.com",
    role: "Salesman",
    status: "Inactive",
    type: "Employee",
    image: Avatar_21,
  },
  {
    id: "13",
    name: "Phyllis Vance",
    company: "Dunder Mifflin",
    email: "phyllisvance@example.com",
    role: "Saleswoman",
    status: "Active",
    type: "Employee",
    image: Avatar_19,
  },
  {
    id: "14",
    name: "Creed Bratton",
    company: "Dunder Mifflin",
    email: "creedbratton@example.com",
    role: "Quality Assurance",
    status: "Inactive",
    type: "Employee",
    image: Avatar_21,
  },
  {
    id: "15",
    name: "Kelly Kapoor",
    company: "Dunder Mifflin",
    email: "kellykapoor@example.com",
    role: "Customer Service Rep",
    status: "Active",
    type: "Employee",
    image: Avatar_19,
  },
];