import {
    Avatar_02,
    Avatar_05,
    Avatar_09,
    Avatar_10,
    Avatar_19,
    Avatar_29,
  } from "../../../../../Routes/ImagePath";
export const data = [
    {
      id: "1",
      ProjectTitle: "Hospital Administration",
      ClientName: "Global Technologies",
      StartDate: "9 Jan 2023",
      EndDate: "10 Apr 2023",
      Status: "Active",
      image: Avatar_19,
      Name_1: "John Doe",
      Avatar_1: Avatar_02,
      Name_2: "Richard Miles",
      Avatar_2: Avatar_09,
      Name_3: "John Smith",
      Avatar_3: Avatar_10,
      Name_4: "Mike Litorus",
      Avatar_4: Avatar_05,
    },
    {
      id: "2",
      ProjectTitle: "Office Management",
      ClientName: "Delta Infotech",
      StartDate: "10 Dec 2023",
      EndDate: "2 May 2023",
      Status: "Active",
      image: Avatar_29,
      Name_1: "John Doe",
      Avatar_1: Avatar_02,
      Name_2: "Richard Miles",
      Avatar_2: Avatar_09,
      Name_3: "John Smith",
      Avatar_3: Avatar_10,
      Name_4: "Mike Litorus",
      Avatar_4: Avatar_05,
    },
    // Add more dummy data to test pagination
    ...Array.from({ length: 18 }, (_, i) => ({
      id: (i + 3).toString(),
      ProjectTitle: `Project ${i + 3}`,
      ClientName: `Client ${i + 3}`,
      StartDate: "1 Jan 2023",
      EndDate: "1 Feb 2023",
      Status: i % 2 === 0 ? "Active" : "Pending",
      image: [Avatar_02, Avatar_05, Avatar_09, Avatar_10, Avatar_19, Avatar_29][i % 6],
      Name_1: "John Doe",
      Avatar_1: Avatar_02,
      Name_2: "Richard Miles",
      Avatar_2: Avatar_09,
      Name_3: "John Smith",
      Avatar_3: Avatar_10,
      Name_4: "Mike Litorus",
      Avatar_4: Avatar_05,
    })),
  ];