import {
  Avatar_02,
  Avatar_05,
  Avatar_09,
  Avatar_10,
  Avatar_11,
} from "../../../../../Routes/ImagePath";

export const leaveReportData = [
  {
    id: 1,
    image: Avatar_05,
    name: "John Doe",
    number: "#0001",
    date: "20 June 2023",
    department: "Design",
    leavetype: "Sick Leave",
    noofdays: "05",
    remainingleave: "08",
    totalleaves: "20",
    totalleavetaken: "12",
    leavecarryforward: "08",
  },
  {
    id: 2,
    image: Avatar_02,
    name: "Richard Miles",
    number: "#0002",
    date: "20 Dec 2022",
    department: "Android Developer",
    leavetype: "Emergency Leave",
    noofdays: "01",
    remainingleave: "09",
    totalleaves: "20",
    totalleavetaken: "17",
    leavecarryforward: "03",
  },
  {
    id: 3,
    image: Avatar_09,
    name: "Mike Litorous",
    number: "#0003",
    date: "20 Dec 2022",
    department: "IOS Developer",
    leavetype: "Sick Leave",
    noofdays: "15",
    remainingleave: "05",
    totalleaves: "20",
    totalleavetaken: "15",
    leavecarryforward: "05",
  },
  {
    id: 4,
    image: Avatar_11,
    name: "John Smith",
    number: "#0004",
    date: "20 Dec 2022",
    department: "Web Developer",
    leavetype: "Parenting Leave",
    noofdays: "03",
    remainingleave: "15",
    totalleaves: "20",
    totalleavetaken: "15",
    leavecarryforward: "05",
  },
  {
    id: 5,
    image: Avatar_10,
    name: "Wilmer Deluna",
    number: "#0005",
    date: "20 Dec 2022",
    department: "Team Leader",
    leavetype: "Sick Leave",
    noofdays: "10",
    remainingleave: "03",
    totalleaves: "20",
    totalleavetaken: "15",
    leavecarryforward: "05",
  },
]; 