import {
  Avatar_03,
  Avatar_05,
  Avatar_09,
  Avatar_10,
  Avatar_11,
} from "../../../../../Routes/ImagePath";

export const dailyReportData = [
  {
    id: 1,
    image: Avatar_03,
    name: "John Doe",
    number: "#0001",
    date: "20 Dec 2023",
    department: "Design",
    status: "Week off",
  },
  {
    id: 2,
    image: Avatar_09,
    name: "Richard Miles",
    number: "#0002",
    date: "20 Dec 2023",
    department: "Web Developer",
    status: "Absent",
  },
  {
    id: 3,
    image: Avatar_10,
    name: "John Smith",
    number: "#0003",
    date: "20 Dec 2023",
    department: "Android Developer",
    status: "Week off",
  },
  {
    id: 4,
    image: Avatar_05,
    name: "Mike Litorus",
    number: "#0004",
    date: "20 Dec 2023",
    department: "IOS Developer",
    status: "Week off",
  },
  {
    id: 5,
    image: Avatar_11,
    name: "Wilmer Deluna",
    number: "#0005",
    date: "20 Dec 2023",
    department: "Team Leader",
    status: "Week off",
  },
  // Additional data
  {
    id: 6,
    image: Avatar_03,
    name: "Sarah Parker",
    number: "#0006",
    date: "20 Dec 2023",
    department: "HR & Finance",
    status: "Present",
  },
  {
    id: 7,
    image: Avatar_09,
    name: "Emma Watson",
    number: "#0007",
    date: "20 Dec 2023",
    department: "Finance",
    status: "Present",
  },
  {
    id: 8,
    image: Avatar_10,
    name: "Chris Evans",
    number: "#0008",
    date: "20 Dec 2023",
    department: "Development",
    status: "Absent",
  },
  {
    id: 9,
    image: Avatar_05,
    name: "Olivia Brown",
    number: "#0009",
    date: "20 Dec 2023",
    department: "Designing",
    status: "Present",
  },
  {
    id: 10,
    image: Avatar_11,
    name: "Liam Johnson",
    number: "#0010",
    date: "20 Dec 2023",
    department: "Development",
    status: "Week off",
  },
  {
    id: 11,
    image: Avatar_03,
    name: "Sophia Lee",
    number: "#0011",
    date: "20 Dec 2023",
    department: "HR & Finance",
    status: "Absent",
  },
  {
    id: 12,
    image: Avatar_09,
    name: "James Smith",
    number: "#0012",
    date: "20 Dec 2023",
    department: "Finance",
    status: "Present",
  },
  {
    id: 13,
    image: Avatar_10,
    name: "Mia Williams",
    number: "#0013",
    date: "20 Dec 2023",
    department: "Designing",
    status: "Present",
  },
  {
    id: 14,
    image: Avatar_05,
    name: "Benjamin Miller",
    number: "#0014",
    date: "20 Dec 2023",
    department: "Development",
    status: "Absent",
  },
  {
    id: 15,
    image: Avatar_11,
    name: "Charlotte Davis",
    number: "#0015",
    date: "20 Dec 2023",
    department: "HR & Finance",
    status: "Week off",
  },
];